In [3]:
%config Completer.use_jedi = False

## GPT Dev work

**Import the initial training data (Shakespeare's works)**

In [4]:
!wget https://raw.githubusercontent.com/karpathy/ng-video-lecture/master/input.txt

--2023-09-12 17:07:28--  https://raw.githubusercontent.com/karpathy/ng-video-lecture/master/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt.1’

input.txt.1         100%[===================>]   1.06M  6.90MB/s    in 0.2s    

2023-09-12 17:07:29 (6.90 MB/s) - ‘input.txt.1’ saved [1115394/1115394]



In [5]:
with open("input.txt", 'r', encoding='utf-8') as f:
    text = f.read()

---

**Sense Checks**


In [6]:
print(f"Number of lines {len(text)}")

Number of lines 1115394


In [7]:
print(text[:250])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.



**Extract Characters**

In [8]:
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(' '.join(chars))
print(f'Unique char count: {vocab_size}')


   ! $ & ' , - . 3 : ; ? A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z
Unique char count: 65


**Create encoding/decoding**

In [9]:
stoi = { ch:i for i,ch in enumerate(chars) } #fun fact: stoi = C++ library for converting strings -> integers.
itos = { i:ch for i,ch in enumerate(chars) }

In [10]:
print(stoi) # ch -> i

{'\n': 0, ' ': 1, '!': 2, '$': 3, '&': 4, "'": 5, ',': 6, '-': 7, '.': 8, '3': 9, ':': 10, ';': 11, '?': 12, 'A': 13, 'B': 14, 'C': 15, 'D': 16, 'E': 17, 'F': 18, 'G': 19, 'H': 20, 'I': 21, 'J': 22, 'K': 23, 'L': 24, 'M': 25, 'N': 26, 'O': 27, 'P': 28, 'Q': 29, 'R': 30, 'S': 31, 'T': 32, 'U': 33, 'V': 34, 'W': 35, 'X': 36, 'Y': 37, 'Z': 38, 'a': 39, 'b': 40, 'c': 41, 'd': 42, 'e': 43, 'f': 44, 'g': 45, 'h': 46, 'i': 47, 'j': 48, 'k': 49, 'l': 50, 'm': 51, 'n': 52, 'o': 53, 'p': 54, 'q': 55, 'r': 56, 's': 57, 't': 58, 'u': 59, 'v': 60, 'w': 61, 'x': 62, 'y': 63, 'z': 64}


In [11]:
print(itos) # i -> ch

{0: '\n', 1: ' ', 2: '!', 3: '$', 4: '&', 5: "'", 6: ',', 7: '-', 8: '.', 9: '3', 10: ':', 11: ';', 12: '?', 13: 'A', 14: 'B', 15: 'C', 16: 'D', 17: 'E', 18: 'F', 19: 'G', 20: 'H', 21: 'I', 22: 'J', 23: 'K', 24: 'L', 25: 'M', 26: 'N', 27: 'O', 28: 'P', 29: 'Q', 30: 'R', 31: 'S', 32: 'T', 33: 'U', 34: 'V', 35: 'W', 36: 'X', 37: 'Y', 38: 'Z', 39: 'a', 40: 'b', 41: 'c', 42: 'd', 43: 'e', 44: 'f', 45: 'g', 46: 'h', 47: 'i', 48: 'j', 49: 'k', 50: 'l', 51: 'm', 52: 'n', 53: 'o', 54: 'p', 55: 'q', 56: 'r', 57: 's', 58: 't', 59: 'u', 60: 'v', 61: 'w', 62: 'x', 63: 'y', 64: 'z'}


In [12]:
encode = lambda s: [stoi[c] for c in s] # Encodes characters in a string as an array of integers
decode = lambda l: ''.join([itos[i] for i in l]) # Decodes integer array back to characters

In [13]:
print("hello world!")
print(encode("hello world!"))
print(decode(encode("hello world!")))

hello world!
[46, 43, 50, 50, 53, 1, 61, 53, 56, 50, 42, 2]
hello world!


**Encode & store the entire text**

In [14]:
import torch
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:250])

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
      

**Split out the training and validation data sets**

In [15]:
n = int(0.9* len(data))
train_data = data[:n]
val_data = data[n:]

**Create the transformer inputs and targets**

In [16]:
block_size = 8
train_data[:block_size + 1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [17]:
x = train_data[:block_size]
y = train_data[1: block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target= y[t]
    print(f"{t}: when the input is {context} the target: {target}")

0: when the input is tensor([18]) the target: 47
1: when the input is tensor([18, 47]) the target: 56
2: when the input is tensor([18, 47, 56]) the target: 57
3: when the input is tensor([18, 47, 56, 57]) the target: 58
4: when the input is tensor([18, 47, 56, 57, 58]) the target: 1
5: when the input is tensor([18, 47, 56, 57, 58,  1]) the target: 15
6: when the input is tensor([18, 47, 56, 57, 58,  1, 15]) the target: 47
7: when the input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) the target: 58


In [18]:
torch.manual_seed(1337)
batch_size = 4 # the number of independent sequences to be processed in parallel
block_size = 8 # the maximum context length for predictions

def get_batch(split):
    # Generate a small batch of data of input x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,)) # Get batch_size random integers between 0 and the data
    x = torch.stack([data[i : i + block_size] for i in ix]) # 4 rows of 8 random encoded character sets
    y = torch.stack([data[i + 1: i + block_size + 1] for i in ix]) # the same as the above, offset by one (targets)
    return x, y

xb, yb = get_batch('train')
print(xb.shape)
print(xb)
print(yb.shape)
print(yb)

print('---')

for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, :t+1]
        target = yb[b, t]
        print(f"{b},{t}: when the input is {context} the target is: {target}")

torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])
---
0,0: when the input is tensor([24]) the target is: 43
0,1: when the input is tensor([24, 43]) the target is: 58
0,2: when the input is tensor([24, 43, 58]) the target is: 5
0,3: when the input is tensor([24, 43, 58,  5]) the target is: 57
0,4: when the input is tensor([24, 43, 58,  5, 57]) the target is: 1
0,5: when the input is tensor([24, 43, 58,  5, 57,  1]) the target is: 46
0,6: when the input is tensor([24, 43, 58,  5, 57,  1, 46]) the target is: 43
0,7: when the input is tensor([24, 43, 58,  5, 57,  1, 46, 43]) the target is: 39
1,0: when the input is tensor([44]) the target is: 53
1,1: when the input is t

**Feed the inputs into a NN**

In [19]:
import torch
import torch.nn as nn
from torch.nn import functional as F

torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        #each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B, T) tensor or integers
        logits = self.token_embedding_table(idx) # (Batch [4] by Time [8] by Channel [vocab_size] tensor)
        loss = None
        
        if targets is not None:
            # Convert dimenions from B, T ,C -->  B, C, T so that we can use F.cross_entropy
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            # Negative loglikelihood loss
            loss = F.cross_entropy(logits, targets)
        
        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx
        

                                                         

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)
print(decode(m.generate(idx= torch.zeros((1,1), dtype=torch.long), max_new_tokens=100)[0].tolist()))

torch.Size([32, 65])
tensor(4.8786, grad_fn=<NllLossBackward0>)

SKIcLT;AcELMoTbvZv C?nq-QE33:CJqkOKH-q;:la!oiywkHjgChzbQ?u!3bLIgwevmyFJGUGp
wnYWmnxKWWev-tDqXErVKLgJ


**Create and test a basic Optimiser**

In [20]:
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [22]:
batch_size = 32
for steps in range(1000):

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())

2.491579532623291


In [23]:
print(print(decode(m.generate(idx= torch.zeros((1,1), dtype=torch.long), max_new_tokens=500)[0].tolist())))


ORO:
ARI m s, baidend RDUMo mbewhith le;
Calu oro my oumeff e in be'dithathechoweds rerg s jerphel,

I; anthysbears Ifo angithanavinonkead otothe he ERWh chore:
NGessuio, b:


F fim, lt bo me,

t chaye solll wer, man'dis l od Reef ghe y f bowingh's s apalversth foor anithiseerdimare,



ARGBu tathittese ft bly, wod. hmurghe t 'd hong gsithoow finche EOMATon'd CHe t wenedinthevedis ankec d g bee'shoungipady, leabuncris?

And;
INULLUMASowimy ale?
Theradad sto.
An whal
Has
ONCowan y RI m ORENTEreot
None


**A Mathematical Example of the  Self Attention Trick**

In [27]:
# Example

torch.manual_seed(1337)
B,T,C = 4, 8, 2 #Batch, Time, Channel
x = torch.randn(B, T, C)

In [53]:
# v1 example

# we want x[b,t] = mean_{i<=t} x[b, i]

xbow = torch.zeros((B,T,C)) # bow => bag of words, a term for averaging up a ton of words
for b in range(B):
    for t in range(T):
        xprev = x[b, :t+1] # (t, C) - because you've dereferenced B, and extracted out t variables
        xbow[b,t] = torch.mean(xprev, 0) # average across time leaving a vector of C

In [54]:
# v2 example

wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True) # (B, T, T) @ (B, T, C) ----> (B, T, C)
xbow2 = wei @ x
torch.allclose(xbow, xbow2)

True

In [52]:
# xbow and xbow2 are equal, for example
xbow[0],  xbow2[0]

(tensor([[ 0.1808, -0.0700],
         [-0.0894, -0.4926],
         [ 0.1490, -0.3199],
         [ 0.3504, -0.2238],
         [ 0.3525,  0.0545],
         [ 0.0688, -0.0396],
         [ 0.0927, -0.0682],
         [-0.0341,  0.1332]]),
 tensor([[ 0.1808, -0.0700],
         [-0.0894, -0.4926],
         [ 0.1490, -0.3199],
         [ 0.3504, -0.2238],
         [ 0.3525,  0.0545],
         [ 0.0688, -0.0396],
         [ 0.0927, -0.0682],
         [-0.0341,  0.1332]]))

In [63]:
#  v3: use Softmax
tril = torch.tril(torch.ones(T,T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf')) # Wherever trill == 0, set weights to negative infinity
wei = F.softmax(wei, dim=-1) # softmax is a normalisation operation (it exponentiates everything and divides by the sum).  
wei

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

In [85]:
#  v4: Self-Attention (a communication mechanism)
# N.B. Every single token @ each section will emit 2 vectors, a query [what am I looking for] and a key [what do I contain].
# We then get affinities between tokens in a sequence by doing a dot product between the key and the queries.
# This becomes Wei.
# If you're interested in the contents of the token, then this is where the value communicates this.

B, T ,C = 4, 8, 32
x = torch.randn(B, T, C)
tril = torch.tril(torch.ones(T,T))

# Old approach for the uniform weights
# wei = torch.zeros((T,T))


# let's see a single head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)

# All of the tokens produce a key array and query array in parallel across the different batches and times (no communication yet).
k = key(x) # B, T, head_size[16]
q = query(x) # B, T, head_size[16]
v = value(x)

wei = k @ q.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) -> (B, T, T)

wei = wei.masked_fill(tril == 0, float('-inf')) # Wherever trill == 0, set weights to negative infinity
wei = F.softmax(wei, dim=-1) # softmax is a normalisation operation (it exponentiates everything and divides by the sum).  
# out = wei @ x
out = wei @ v

out.shape

torch.Size([4, 8, 16])

In [32]:
x[0]

tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.9152],
        [ 0.6258,  0.0255],
        [ 0.9545,  0.0643],
        [ 0.3612,  1.1679],
        [-1.3499, -0.5102],
        [ 0.2360, -0.2398],
        [-0.9211,  1.5433]])

In [33]:
xbow[0] # cumulative average as you go down across time

tensor([[ 0.1808, -0.0700],
        [-0.0894, -0.4926],
        [ 0.1490, -0.3199],
        [ 0.3504, -0.2238],
        [ 0.3525,  0.0545],
        [ 0.0688, -0.0396],
        [ 0.0927, -0.0682],
        [-0.0341,  0.1332]])

*Matrix Multiplication - Example*

In [38]:
torch.manual_seed(42)
a = torch.tril(torch.ones(3,3))
a = a / torch.sum(a, 1, keepdim = True)
b = torch.randint(0, 10, (3,2)).float()
c = a @ b
print ('a=')
print (a)
print ('---')
print ('b=')
print (b)
print ('---')
print ('c=')
print (c)


a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
---
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
---
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])
